#!/bin/bash
python3 -m venv venv
source venv/bin/activate
pipout=$(pip install -r requirements.txt)
echo $pipout
pyte=$(pip install pytest)
echo $pyte
tes=$(pytest)
echo $tes
# start=$(uvicorn app.main:app)
# echo $start
exit 0