name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --max-line-length=120 --ignore=E501,W503
      - name: Type check with mypy
        run: |
          pip install mypy
          mypy . --ignore-missing-imports --disallow-untyped-defs
      - name: Format code with black
        run: |
          pip install black
          black .
      - name: Build package
        run: |
          pip install build
          python -m build
          
  test:
    needs: build
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.9]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          
      - name: Run tests with pytest
        run: pytest --maxfail=1 --disable-warnings --tb=short
